### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by tongpu** [adfinis/adsy-trainings#37]
This repository currently doesn't provide LICENSE information.

**Comment by eyenx** [comment]
https://github.com/adfinis-sygroup/adsy-trainings/blob/master/LICENSE

**Comment by hairmare** [comment]
That looks a bit like it should be called `THIRD_PARTY_LICENSE.md` and the there should be an actual LICENSE containing "Creative Commons Attribution-Share Alike 3.0 Unported". That would also help GitHub pick up on the actual license.

**Comment by tongpu** [comment]
> That looks a bit like it should be called `THIRD_PARTY_LICENSE.md` and the there should be an actual LICENSE containing "Creative Commons Attribution-Share Alike 3.0 Unported". That would also help GitHub pick up on the actual license.

You're right. I didn't realize that there is an actual `LICENSE` file, I only saw that GitHub didn't show license information.
